import * as assert from "node:assert/strict";
/* eslint-disable @typescript-eslint/no-explicit-any */
import { execSync } from "node:child_process";
import fs from "node:fs";
import { rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { getAiConfig } from "../src/lib/ai/ai-config";
import { OllamaClient } from "../src/lib/ai/ollama/ollama-client";
import { OllamaFrameExtractor } from "../src/lib/ai/ollama/ollama-frame-extractor";
import { GoogleDriveMediaReader } from "../src/lib/google-drive/google-drive-media-reader";

async function main() {
  console.log("==================================================================");
  console.log("MANUAL SMOKE TEST: Real local Ollama visual-inference execution");
  console.log("==================================================================");

  // Set environment overrides for the smoke test
  process.env.AI_PROVIDER = "OLLAMA";
  process.env.OLLAMA_BASE_URL = "http://127.0.0.1:11434";
  process.env.OLLAMA_MODEL = "qwen3-vl:2b-instruct";
  process.env.OLLAMA_FRAME_COUNT = "1";
  process.env.OLLAMA_REQUEST_TIMEOUT_MS = "600000";
  process.env.OLLAMA_MAX_CONCURRENCY = "1";

  const config = getAiConfig(process.env);
  const dummyVideoPath = join(tmpdir(), `dummy-video-${Date.now()}.mp4`);

  console.log("Step 1: Generating a 5-second dummy local MP4 video file using FFmpeg...");
  try {
    execSync(
      `ffmpeg -y -f lavfi -i testsrc=duration=5:size=320x240:rate=30 -pix_fmt yuv420p "${dummyVideoPath}"`,
      { stdio: "ignore" }
    );
    console.log(`- Created dummy video at: ${dummyVideoPath}`);
  } catch (err: any) {
    console.error("Failed to generate dummy video using FFmpeg. Make sure ffmpeg is in your PATH.", err.message);
    process.exit(1);
  }

  console.log("\nStep 2: Monkey-patching GoogleDriveMediaReader stream handler...");
  // Re-route the media reader stream downloader to fetch our local dummy file directly
  (GoogleDriveMediaReader as any).getDownloadStream = async (userId: string, asset: any) => {
    void userId;
    void asset;
    return fs.createReadStream(dummyVideoPath);
  };
  console.log("- GoogleDriveMediaReader successfully stubbed to stream dummy video.");

  const mockAsset = {
    id: "smoke-asset-id-12345",
    userId: "smoke-user-id-54321",
    provider: "GOOGLE_DRIVE",
    status: "VALIDATED",
    originalName: "dummy-video-smoke.mp4",
    expectedSize: BigInt(fs.statSync(dummyVideoPath).size),
    actualSize: BigInt(fs.statSync(dummyVideoPath).size),
    durationMs: 5000, // 5 seconds
  };

  console.log("\nStep 3: Running OllamaFrameExtractor on the video...");
  let extracted;
  try {
    extracted = await OllamaFrameExtractor.extractFrames({
      userId: "smoke-user-id-54321",
      asset: mockAsset,
      frameCount: config.ollamaFrameCount,
    });
    console.log(`- Successfully extracted ${extracted.base64Frames.length} frames.`);
    console.log(`- Spaced timestamps: [${extracted.timestamps.join(", ")}]`);
  } catch (err: any) {
    console.error("Frame extraction failed:", err);
    await cleanup();
    process.exit(1);
  }

  console.log("\nStep 4: Executing real local Ollama visual inference (qwen3-vl:2b-instruct)...");
  console.log(`- Connecting to: ${config.ollamaBaseUrl}`);
  console.log(`- Target Model: ${config.ollamaModel}`);
  console.log("- Sending visual payload (base64 image frames & prompts)...");

  const client = new OllamaClient({
    baseUrl: config.ollamaBaseUrl,
    model: config.ollamaModel,
    timeoutMs: config.ollamaRequestTimeoutMs,
  });

  try {
    const analysis = await client.generateVideoMetadata({
      durationSeconds: mockAsset.durationMs / 1000,
      timestamps: extracted.timestamps,
      base64Frames: extracted.base64Frames,
    });

    console.log("\n==================================================================");
    console.log("SMOKE TEST METADATA OUTPUT GENERATED BY OLLAMA:");
    console.log("==================================================================");
    console.log(`Title:     "${analysis.title}"`);
    console.log(`Caption:   "${analysis.caption}"`);
    console.log(`Hashtags:  ${JSON.stringify(analysis.hashtags)}`);
    console.log(`Timestamp: ${analysis.thumbnailTimestampSeconds} seconds`);
    console.log("==================================================================");

    // Validation asserts
    console.log("\nStep 5: Verifying Ollama output schema and values...");
    assert.ok(analysis.title.trim().length >= 3, "Title too short");
    assert.ok(analysis.title.trim().length <= 255, "Title too long");
    assert.ok(!analysis.title.includes("\n"), "Title contains newlines");
    assert.ok(analysis.caption.trim().length >= 10, "Caption too short");
    assert.ok(analysis.caption.trim().length <= 2200, "Caption too long");
    assert.equal(analysis.hashtags.length, 5, "Hashtags count must be exactly five");

    const uniqueHashtags = new Set(analysis.hashtags.map((h) => h.toLowerCase()));
    assert.equal(uniqueHashtags.size, 5, "Hashtags are not unique");

    for (const hashtag of analysis.hashtags) {
      assert.ok(hashtag.startsWith("#"), `Hashtag "${hashtag}" does not start with #`);
    }

    assert.ok(analysis.thumbnailTimestampSeconds >= 0, "Timestamp below zero");
    assert.ok(analysis.thumbnailTimestampSeconds <= 5.0, "Timestamp beyond duration");

    console.log("Ã¢Å“â€œ Verification successful: output matches all strict validation rules.");
  } catch (err: any) {
    console.error("Ollama execution or validation assertion failed:", err);
    await cleanup();
    process.exit(1);
  }

  await cleanup();
  console.log("\nMANUAL SMOKE TEST PASSED SUCCESSFULLY.");

  async function cleanup() {
    console.log("\nStep 6: Purging temporary files...");
    if (fs.existsSync(dummyVideoPath)) {
      await rm(dummyVideoPath, { force: true });
    }
    console.log("- Temp video file deleted.");
  }
}

main().catch((err) => {
  console.error("Unhandled smoke test exception:", err);
  process.exit(1);
});
